### ISSUE TITLE
Raises error on Android by codes for animation

### ISSUE THREAD

**Issue by januswel** [YutamaKotaro/react-native-flex-keyboard-spacer#4]
![screen shot 0028-10-26 at 15 05 39](https://cloud.githubusercontent.com/assets/43239/19716316/16551ff6-9b96-11e6-9e3e-be7ea67f0cc9.png)

**Comment by YutamaKotaro** [comment]
current version work on Android, but have a bug, that trackMode does not work well.
I 'll try to fix this.
